//! Kairos `kairos-core` build script.
//!
//! All kernel configuration is *compile-time configuration* ("配置即代码"):
//! plain environment variables are baked into constants by `config.rs`.
//! The kernel never hard-codes policy parameters.
//!
//! To keep the generated constants toolchain-agnostic (const `str` matching
//! is not stable on every nightly), this script writes the final values as
//! *literals* into `$OUT_DIR/kairos_cfg.rs`, which `config.rs` then
//! `include!`s — no runtime parsing, no const-eval gymnastics.

use std::{env, fs, path::PathBuf};

fn main() {
    // Re-run whenever the operator changes any KAIROS_* knob.
    for var in [
        "KAIROS_SCHED_POLICY",
        "KAIROS_QUANTUM_MS",
        "KAIROS_HEAP_MIB",
        "KAIROS_REALTIME_DEMO",
        "KAIROS_TEST",
        "KAIROS_LOG_LEVEL",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }

    let sched = env::var("KAIROS_SCHED_POLICY").unwrap_or_else(|_| "weighted".into());
    let sched = match sched.as_str() {
        "rr" | "round-robin" | "RoundRobin" => "RoundRobin",
        "weighted" | "wrr" | "WeightedRoundRobin" => "WeightedRoundRobin",
        "edf" | "earliest-deadline-first" | "EarliestDeadlineFirst" => "EarliestDeadlineFirst",
        other => panic!("invalid KAIROS_SCHED_POLICY `{other}` (expected rr | weighted | edf)"),
    };

    let quantum_ms = env::var("KAIROS_QUANTUM_MS")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(10);
    let heap_mib = env::var("KAIROS_HEAP_MIB")
        .ok()
        .and_then(|v| v.parse::<usize>().ok())
        .unwrap_or(64);
    let rt = env::var("KAIROS_REALTIME_DEMO")
        .ok()
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);
    let test = env::var("KAIROS_TEST")
        .ok()
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    let log = env::var("KAIROS_LOG_LEVEL").unwrap_or_else(|_| "info".into());
    let log = match log.as_str() {
        "trace" => "Trace",
        "debug" => "Debug",
        "info" => "Info",
        "warn" => "Warn",
        "error" => "Error",
        other => panic!("invalid KAIROS_LOG_LEVEL `{other}` (trace|debug|info|warn|error)"),
    };

    let generated = format!(
        "// GENERATED by kairos-core/build.rs — do not edit.\n\
         pub const SCHED_POLICY: SchedPolicy = SchedPolicy::{sched};\n\
         pub const QUANTUM_MS: u64 = {quantum_ms};\n\
         pub const HEAP_MIB: usize = {heap_mib};\n\
         pub const REALTIME_DEMO: bool = {rt};\n\
         pub const TEST_MODE: bool = {test};\n\
         pub const LOG_LEVEL: LogLevel = LogLevel::{log};\n"
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out.join("kairos_cfg.rs"), generated).expect("write kairos_cfg.rs");
    println!("cargo:rerun-if-changed=build.rs");
}